name: sahil_guvenlik
description: "Sahil Güvenlik Eğitim Platformu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.15
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  video_player_web: ^2.3.2  # WEB DESTEĞİ EKLENDI
  chewie: ^1.7.2
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/videos/